### ISSUE TITLE
the `Dashing-devel' branch.

### ISSUE THREAD

**Issue by harderthan** [joonr7/HesaiLidar_General_ROS2#1]
Hello, Junyoung. Nice to meet you here again.
**Could you create a new branch for dashing ros2 version?** I developed this driver for Dashing version.
It would be nice if the branch name is `dashing-devel`. 
https://github.com/harderthan/HesaiLidar_General_ROS2/tree/dashing-devel
Thanks.

**Comment by joonr7** [comment]
Sure. I'd love to.
